TERMUX_PKG_HOMEPAGE=https://github.com/termux/libposix-shm
TERMUX_PKG_DESCRIPTION="System V shared memory emulation on Android using ashmem"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.5
TERMUX_PKG_SRCURL=https://github.com/asklo339/Tup/releases/download/Tet/libshm.tar.gz
TERMUX_PKG_SHA256=c487e4e1d9aed84c803332feaef0ac493fbe31132572f75b578e3c1ed825ed43
TERMUX_PKG_BREAKS="libandroid-shmem-dev"
TERMUX_PKG_REPLACES="libandroid-shmem-dev"
TERMUX_PKG_BREAKS="libposix-shm-dev"
TERMUX_PKG_REPLACES="libposix-shm-dev"
TERMUX_PKG_BUILD_IN_SRC=true
